#@baseUrl=http://localhost:3000
#@baseUrl=https://wom21-notes.azurewebsites.net
@baseUrl=https://agile-spire-87708.herokuapp.com
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MTQxZTkzNGQ4ODYwMDdhZTQwMzMzMWYiLCJlbWFpbCI6ImphbmVAZG9lLmNvbSIsImlhdCI6MTYzMjMxMTEwMiwiZXhwIjoxNjMyMzk3NTAyfQ.XpUoHtxn_Mz9n4rM8tu9jZyS2QhK4riqLHR7p7bT8TQ
GET {{baseUrl}}


### Login
POST {{baseUrl}}/users/login
Content-Type: application/json

{  "email": "jane@doe.com",  "password": "Password123"}

###

GET {{baseUrl}}/notes
Authorization: Bearer {{token}}
###

GET {{baseUrl}}/notes/archived
Authorization: Bearer {{token}}

###
POST {{baseUrl}}/notes
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "text": "Köp bröd"
}
###
GET {{baseUrl}}/notes/613e33f6de9a42cdd92308ff


###
PUT {{baseUrl}}/notes/613e370a4bf62b8fca0d1c8d
Content-Type: application/json

{
    "text": "Köp smör"
}

###
DELETE {{baseUrl}}/notes/61487ad5e6e511bb58232d44
Authorization: Bearer {{token}}
